# Generated by Django 5.2 on 2025-10-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrow',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Used to maintain row order within each category.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1/1'), (2, 'Year 1/2'), (3, 'Year 2/1'), (4, 'Year 2/2'), (5, 'Year 3/1'), (6, 'Year 3/2'), (7, 'Year 4/1'), (8, 'Year 4/2')]),
        ),
        migrations.AlterField(
            model_name='creditrow',
            name='row_type',
            field=models.CharField(choices=[('general', 'General Education'), ('core', 'Core Education'), ('free', 'Free Elective'), ('plo', 'PLO-based Category')], max_length=10),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='clo_edit_password',
            field=models.CharField(blank=True, help_text='Password required to unlock the CLO–KSEC Mapping interface.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='password',
            field=models.CharField(blank=True, help_text='Password required to unlock the edit mode of the main credit table.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ksecitem',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ksecitem',
            name='type',
            field=models.CharField(choices=[('K', 'Knowledge'), ('S', 'Skills'), ('E', 'Ethics'), ('C', 'Character')], max_length=1),
        ),
    ]
